### ISSUE TITLE
Don't crash on sockets

### ISSUE THREAD

**Issue by dgentry** [dgentry/mergeinator#2]
File "/Users/gentry/.virtualenv/v/lib/python3.7/site-packages/mergeinator/mergeinator.py", line 292, in move
    shutil.move(src, dest)
  File "/Users/gentry/.virtualenv/v/lib/python3.7/shutil.py", line 574, in move
    symlinks=True)
  File "/Users/gentry/.virtualenv/v/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('Library/Developer/Xcode/GPUToolsAgent.sock', '/Volumes/thai/gentry/Library/Developer/Xcode/GPUToolsAgent.sock', "[Errno 102] Operation not supported on socket: 'Library/Developer/Xcode/GPUToolsAgent.sock'")]

**Comment by dgentry** [comment]
Here's a secondary exception when trying to rename a Cross-device Link that was a socket.  It's possible that if we handled sockets, this move of a cross-device link wouldn't have been a problem, but we should probably also handle cross-device links as sensibly as possible anyway.

```
/Volumes/boof/Users/gentry/Library/Group Containers/google_drive/tmpRYTR7T= ?--> ./. . .  Safe.  Move? [Y/n] y
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Cross-device link: '/Volumes/boof/Users/gentry/Library/Group Containers/google_drive/tmpRYTR7T' -> 'Library/Group Containers/google_drive/tmpRYTR7T'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gentry/.virtualenv/3/bin/merge", line 8, in <module>
    sys.exit(cli())
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/merge.py", line 27, in cli
    mergeinator.do_merge(source, destination, 0, yes_flag=yes, dry_run_flag=dryrun)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/mergeinator.py", line 333, in do_merge
    walk(src, dest_dir, level)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/mergeinator.py", line 433, in walk
    walk(abs_f, dest_file, level + 1)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/mergeinator.py", line 433, in walk
    walk(abs_f, dest_file, level + 1)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/mergeinator.py", line 433, in walk
    walk(abs_f, dest_file, level + 1)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/mergeinator.py", line 351, in walk
    move(abs_f, dest_file)
  File "/Users/gentry/.virtualenv/3/lib/python3.8/site-packages/mergeinator/mergeinator.py", line 294, in move
    shutil.move(src, dest)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 102] Operation not supported on socket: '/Volumes/boof/Users/gentry/Library/Group Containers/google_drive/tmpRYTR7T'
```

**Comment by dgentry** [comment]
Mergeinator handles both sockets and cross-device links as of b69fc13.
